- aiconsole/api/endpoints/projects/choose.py
- aiconsole/materials/core/agents_list.toml
- aiconsole/materials/core/environment.toml
- aiconsole/materials/core/materials_list.toml
- aiconsole/materials/material.py
- aiconsole/utils/initialize_project_directory.py
- poetry.lock
- pyproject.toml
> ACD-313 ModuleNotFoundError: No module named '_tkinter'

- web/src/components/MaterialItem.tsx
- web/src/components/inputs/CodeInput.tsx
- web/src/components/inputs/EnumInput.tsx
- web/src/components/inputs/TextInput.tsx
- web/src/components/pages/MaterialPage.tsx
- web/src/components/pages/MaterialsPage.tsx
- web/src/store/MetarialSlice.ts
- web/src/types/types.ts
Tasks: [ACD-340](https://10clouds.atlassian.net/browse/ACD-340), [ACD-331](https://10clouds.atlassian.net/browse/ACD-331), [ACD-334](https://10clouds.atlassian.net/browse/ACD-334)
Made aiconsole materials (core) read only
Removed trash icon (delete option ) for core materials
[ACD-340]: https://10clouds.atlassian.net/browse/ACD-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ACD-331]: https://10clouds.atlassian.net/browse/ACD-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ACD-334]: https://10clouds.atlassian.net/browse/ACD-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FE] feat/readonlu aiconsole materials 

- web/src/components/MarkdownPreview.tsx
- web/src/components/MaterialTable.tsx
- web/src/components/inputs/CodeInput.tsx
- web/src/components/inputs/TextInput.tsx
- web/src/components/pages/MaterialPage.tsx
- web/src/components/pages/MaterialsPage.tsx
- web/src/store/MetarialSlice.ts
- web/src/types/types.ts
[ACD-378](https://10clouds.atlassian.net/browse/ACD-378)
[ACD-378]: https://10clouds.atlassian.net/browse/ACD-378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: fixing minor ui issues

- web/src/components/recentProjects/RecentProjects.tsx
- web/src/components/system/OpenAiApiKeyForm.tsx
- web/src/store/ProjectSlice.ts
- web/src/types/types.ts
**Task:** [ACD-460](https://10clouds.atlassian.net/browse/ACD-460)
[ACD-460]: https://10clouds.atlassian.net/browse/ACD-460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add screen with input if no OpenAI API key

- .github/workflows/electron-publish.yml
Changed
- set the Windows mode
> [gha-pipeline]

- frontend/src/utils/showNotification.ts
**Task:** [ACD-490](https://10clouds.atlassian.net/browse/ACD-490)
[ACD-490]: https://10clouds.atlassian.net/browse/ACD-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: fine tune notification's styling

- frontend/src/components/system/Button.tsx
- frontend/src/components/system/ConfirmationModal.tsx
**Task:** [ACD-491: Gdy naciskam tutaj enter - zamyka sie modal a nie akceptuje z "Yes"](https://10clouds.atlassian.net/browse/ACD-491)
> fix: delete material on enter key press

- frontend/package.json
Changed
- the `optionalDependencies` set with the `fs-xattr` for the frontend
> [fs-xattr_fix_for_win32]

- electron/forge.config.cjs
Changed
- added `authors: 10Clouds` to the `electron/forge.config.cjs`
> [maker-squirrel-authors]

- .github/workflows/electron-publish.yml
Changed
- modified the step related to MAcOS build, by adding the singing process
> [certs_sign_process]

- frontend/src/components/chat/messages/CodeMessage.tsx
- frontend/src/components/modals/GlobalSettings.tsx
- frontend/src/components/modals/SettingsModal.tsx
- frontend/src/components/system/Button.tsx
- frontend/src/components/system/TopBar.tsx
- frontend/src/store/ProjectSlice.ts
Task: [ACD-88](https://10clouds.atlassian.net/browse/ACD-88)
[ACD-88]: https://10clouds.atlassian.net/browse/ACD-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: added global settings modal

- frontend/src/components/history/HeadlinesGroup.tsx
**Task:** [ACD-409](https://10clouds.atlassian.net/browse/ACD-409)
Actions updating the chat title:
- clicking on check mark (✓) button
- clicking outside of the input field
- pressing _Enter_ key
Actions discarding the update:
- clicking on ✕ button
- pressing _Esc_ key
[ACD-409]: https://10clouds.atlassian.net/browse/ACD-409?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: handle events - chat title renaming

- electron/forge.config.cjs
> [linux-name-package]

- backend/pyproject.toml
- electron/forge.config.cjs
- electron/package.json
- frontend/package.json
Changed
- added a `hook` into the `electron/forge.config.cjs`
- set the version to `0.2.1-alpha6`
> [dmg-release-values]

- electron/forge.config.cjs
> [dmg-release-values

- frontend/src/index.css
**Task:** [ACD-480](https://10clouds.atlassian.net/browse/ACD-480)
https://github.com/10clouds/aiconsole/assets/63242859/7b93f515-f1aa-427b-919d-cfbe6c7f3743
[ACD-480]: https://10clouds.atlassian.net/browse/ACD-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: prevent homepage scrollbar from disappearing on hover

- frontend/src/components/Router.tsx
**Task:** [ACD-593: Settings view is not opening even though button is clickable](https://10clouds.atlassian.net/browse/ACD-593)
**Preview:**
https://github.com/10clouds/aiconsole/assets/63242859/e993140a-7876-4a85-ba80-0e0d2b1c65da
> fix: display settings modal on home view

- frontend/src/components/projects/HomeTopBarElements.tsx
- frontend/src/components/projects/ProjectButtons.tsx
- frontend/src/components/projects/RecentProjectsEmpty.tsx
[ACD-611](https://10clouds.atlassian.net/browse/ACD-611)
- Extracted common JSX to separate component that is reused in the welcome screen and the topbar
[ACD-611]: https://10clouds.atlassian.net/browse/ACD-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show project buttons when there is no recent project

- frontend/src/components/common/TopBar.tsx
- frontend/src/components/projects/ProjectTopBarElements.tsx
**Task:** [ACD-613](https://10clouds.atlassian.net/browse/ACD-613)
**Preview:**
https://github.com/10clouds/aiconsole/assets/63242859/8fb91de3-54fd-47e1-94ce-ab0b1d762098
[ACD-613]: https://10clouds.atlassian.net/browse/ACD-613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: close project icon in topbar

- frontend/src/components/projects/RecentProjectsEmpty.tsx
[QUE-559](https://10clouds.atlassian.net/browse/ACD-559)
- small styles fix to not cut the icon and the title on smaller screens
https://github.com/10clouds/aiconsole/assets/25374390/36fc0bd0-c368-48e8-b64d-f0ab2e73e124
[QUE-559]: https://10clouds.atlassian.net/browse/QUE-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix  view styles

- frontend/src/components/settings/GlobalSettingsModal.tsx
[QUE-553](https://10clouds.atlassian.net/browse/ACD-553)
- fixed styles for settings content height to not display unnecessary scrollbars
https://github.com/10clouds/aiconsole/assets/25374390/c65f136f-96ce-431c-a1d2-fc00fbda2467
[QUE-553]: https://10clouds.atlassian.net/browse/QUE-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ACD-553] Incorrect settings height

- frontend/src/components/editables/assets/AssetEditor.tsx
- frontend/src/components/projects/ProjectButtons.tsx
- frontend/src/components/projects/ProjectTopBarElements.tsx
- frontend/src/utils/projects/useProjectFileManager.ts
Task: [ACD-607](https://10clouds.atlassian.net/browse/ACD-607)
[ACD-607]: https://10clouds.atlassian.net/browse/ACD-607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: canceling project choose is working incorrectly

- frontend/src/components/editables/assets/AssetEditor.tsx
- frontend/src/components/editables/assets/TextInput.tsx
[ACD-606](https://10clouds.atlassian.net/browse/ACD-606)
- text input height for usage is adjusted to the text length max to 80px ~ about 3 lines
https://github.com/10clouds/aiconsole/assets/25374390/f37ec636-9585-4bac-a3e1-361f4cf74f4c
[ACD-606]: https://10clouds.atlassian.net/browse/ACD-606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ACD-606] Improvement: Agent's usage textbox size need to be adjusted

- frontend/src/components/editables/sidebar/AssetsSidebarTab.tsx
- frontend/src/components/editables/sidebar/SideBar.tsx
- frontend/src/components/editables/sidebar/SideBarItem.tsx
Tasks:
[ACD-569
](https://10clouds.atlassian.net/browse/ACD-569)
[ACD-570](https://10clouds.atlassian.net/browse/ACD-570)
[ACD-570]: https://10clouds.atlassian.net/browse/ACD-570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: added sorted assets by their status

- frontend/src/components/editables/assets/AssetEditor.tsx
- frontend/src/components/editables/assets/CodeInput.tsx
Task: [ACD-647](https://10clouds.atlassian.net/browse/ACD-647)
[ACD-647]: https://10clouds.atlassian.net/browse/ACD-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fixing infinite loop that happens while changing assets

- frontend/src/utils/editables/useAssetChanged.tsx
[ACD-649](https://10clouds.atlassian.net/browse/ACD-649)
- Discard modal is displayed only when new asset was edited
[ACD-649]: https://10clouds.atlassian.net/browse/ACD-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ACD-649] When I create a new material, and then I try to navigate away I get a discard message

- frontend/src/components/common/icons/RadioCheckedIcon.tsx
- frontend/src/components/editables/sidebar/SideBar.tsx
- frontend/src/components/editables/sidebar/Tab.tsx
- frontend/src/index.css
- frontend/src/main.tsx
- frontend/src/utils/common/noop.ts
- frontend/src/utils/common/useContextMenu.ts
- frontend/src/utils/editables/useContextMenuForEditable.tsx
- frontend/tailwind.config.js
Tasks: 
[ACD-617](https://10clouds.atlassian.net/browse/ACD-617)
[ACD-625](https://10clouds.atlassian.net/browse/ACD-625)
Results
[ACD-617]: https://10clouds.atlassian.net/browse/ACD-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ACD-625]: https://10clouds.atlassian.net/browse/ACD-625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat/ adjusting context menu styles to fit the designs

- frontend/src/components/editables/assets/AssetEditor.tsx
[ACD-662](https://10clouds.atlassian.net/browse/ACD-658)
https://github.com/10clouds/aiconsole/assets/25374390/159bf1fa-28b7-408f-b16e-0df69d20f490
[ACD-662]: https://10clouds.atlassian.net/browse/ACD-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ACD-658]  Przestała się wyświetlać informacja, że asset jest ovewritten

- frontend/src/components/editables/assets/AssetEditor.tsx
- frontend/src/components/editables/chat/ChatPage.tsx
- frontend/src/components/editables/sidebar/SideBarItem.tsx
- frontend/src/store/editables/AgentsSlice.ts
- frontend/src/store/editables/ChatsSlice.ts
- frontend/src/store/editables/MetarialSlice.ts
- frontend/src/store/editables/asset/useAssetStore.ts
- frontend/src/store/editables/chat/ChatSlice.ts
- frontend/src/utils/editables/useAssets.ts
- frontend/src/utils/editables/useChat.ts
Task: [ACD-657](https://10clouds.atlassian.net/browse/ACD-657)
[ACD-657]: https://10clouds.atlassian.net/browse/ACD-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix / making renaming logic reusable

- frontend/src/components/common/Button.tsx
- frontend/src/components/editables/assets/AssetEditor.tsx
- frontend/src/components/editables/sidebar/SideBarItem.tsx
Task: [ACD-644](https://10clouds.atlassian.net/browse/ACD-644)
[ACD-644]: https://10clouds.atlassian.net/browse/ACD-644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: restyling asset saved button to fit figgma design

- frontend/src/components/common/icons/StopIcon.tsx
- frontend/src/components/editables/chat/ChatPage.tsx
- frontend/src/components/editables/chat/GuideMe.tsx
- frontend/src/index.css
Task: [ACD-685](https://10clouds.atlassian.net/browse/ACD-685)
Question: Verify if regenerate has correct logic now (i think it hasnt)
[ACD-685]: https://10clouds.atlassian.net/browse/ACD-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: implementing ui for guide me

- frontend/src/components/Router.tsx
- frontend/src/components/editables/chat/messages/ToolCall.tsx
Task: [ACD-630](https://10clouds.atlassian.net/browse/ACD-630)
[ACD-630]: https://10clouds.atlassian.net/browse/ACD-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: updating color for app background

- frontend/src/components/common/ConfirmationModal.tsx
- frontend/src/components/editables/chat/ChatPage.tsx
Task: [ACD-780](https://10clouds.atlassian.net/browse/ACD-780)
Preview: 
[ACD-780]: https://10clouds.atlassian.net/browse/ACD-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: display modal when switching from active chat

- frontend/src/components/editables/assets/AssetEditor.tsx
Task: [ACD-761](https://10clouds.atlassian.net/browse/ACD-761)
[ACD-761]: https://10clouds.atlassian.net/browse/ACD-761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: reseting asset form on escape

- frontend/src/components/common/icons/SendRotated.tsx
- frontend/src/components/common/icons/SquareFill.tsx
- frontend/src/components/common/icons/StopIcon.tsx
- frontend/src/components/editables/EditorHeader.tsx
- frontend/src/components/editables/InlineEditableObjectName.tsx
- frontend/src/components/editables/chat/AgentAvatar.tsx
- frontend/src/components/editables/chat/ChatPage.tsx
- frontend/src/components/editables/chat/CommandInput.tsx
- frontend/src/components/editables/chat/EmptyChat.tsx
- frontend/src/components/editables/chat/GuideMe.tsx
- frontend/src/components/editables/chat/MessageGroup.tsx
- frontend/src/components/editables/chat/UserInfo.tsx
- frontend/src/components/editables/chat/messages/EditableContentMessage.tsx
- frontend/src/components/editables/chat/messages/MessageControls.tsx
- frontend/src/components/editables/chat/messages/ToolCall.tsx
- frontend/src/index.css
- frontend/tailwind.config.js
Task: [ACD-803](https://10clouds.atlassian.net/browse/ACD-803), [ACD-629](https://10clouds.atlassian.net/browse/ACD-629)
Results:
[ACD-803]: https://10clouds.atlassian.net/browse/ACD-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ACD-629]: https://10clouds.atlassian.net/browse/ACD-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: chat design adjustments

- frontend/package.json
- frontend/src/components/common/Tooltip.tsx
- frontend/src/components/editables/assets/TextInput.tsx
- frontend/src/components/editables/chat/CommandInput.tsx
- frontend/src/components/editables/chat/EmptyChat.tsx
- frontend/tailwind.config.js
- frontend/yarn.lock
**Task:** https://10clouds.atlassian.net/browse/ACD-832
**Preview:**
> feat: add Tooltip from RadixUI

- backend/aiconsole/app.py
- backend/poetry.lock
- backend/pyproject.toml
- electron/.env.example
- electron/package.json
- electron/src/main.ts
- electron/yarn.lock
- frontend/.env.example
- frontend/package.json
- frontend/src/main.tsx
- frontend/yarn.lock
This reverts commit ff65e5ac200aad310fb719ca21ab99dd16953ea3.
> Fix: revert sentry

- frontend/src/components/editables/chat/EmptyChat.tsx
Task: [ACD-853](https://10clouds.atlassian.net/browse/ACD-853)
[ACD-853]: https://10clouds.atlassian.net/browse/ACD-853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: glow image not found

- frontend/package.json
- frontend/src/index.css
- frontend/src/layout.css
- frontend/src/main.tsx
- frontend/yarn.lock
Task: [ACD-838](https://10clouds.atlassian.net/browse/ACD-838)
[ACD-838]: https://10clouds.atlassian.net/browse/ACD-838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: removing mantine dependencies

- frontend/src/components/common/Tooltip.tsx
- frontend/src/components/editables/chat/ChatPage.tsx
- frontend/src/components/editables/chat/CommandInput.tsx
Task: https://10clouds.atlassian.net/browse/ACD-864
> feat: updating chat input styles

- frontend/src/components/editables/chat/ChatPage.tsx
- frontend/src/components/editables/chat/MessageGroup.tsx
- frontend/src/components/editables/chat/UserInfo.tsx
- frontend/src/components/editables/chat/messages/MessageComponent.tsx
- frontend/src/components/editables/chat/messages/MessageControls.tsx
Task: https://10clouds.atlassian.net/browse/ACD-867
> fix: fixed issue with chat width

- backend/aiconsole/preinstalled/materials/onboarding_agent_guide.toml
The problematic byte (0x9d) has been identified and replaced in both assistant.toml and onboarding_agent_guide.toml files. The files have been updated and saved with UTF-8 encoding.
> UTF-8 encoding

- frontend/src/components/common/Button.tsx
- frontend/src/components/editables/assets/AssetEditor.tsx
- frontend/src/components/editables/assets/CodeInput.tsx
- frontend/src/components/editables/assets/TextInput.tsx
- frontend/src/components/settings/GlobalSettingsModal.tsx
- frontend/src/components/settings/OpenAiApiKeyForm.tsx
Task: https://10clouds.atlassian.net/browse/ACD-415
> feat: updating styles for input

- frontend/src/components/common/ContextMenu.tsx
- frontend/src/components/editables/chat/UserInfo.tsx
- frontend/src/components/settings/GlobalSettingsModal.tsx
Task: [ACD-872](https://10clouds.atlassian.net/browse/ACD-872)
[ACD-872]: https://10clouds.atlassian.net/browse/ACD-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: selecting agent in chat does not work

- .github/workflows/on-tag-prerelease.yml
- electron/forge.config.cjs
- electron/package.json
- electron/scripts/propagate_version.py
Changed
- the `electron/scripts/propagate_version.py` was extended by adding the argparse
> [ACD-751/setup-version]

- frontend/src/components/editables/sidebar/SideBarItem.tsx
**Task:** [ACD-878](https://10clouds.atlassian.net/browse/ACD-878)
**Preview:**
https://github.com/10clouds/aiconsole/assets/63242859/49d4b490-8d3d-4283-a918-9955b1ca9b54
[ACD-878]: https://10clouds.atlassian.net/browse/ACD-878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: rename assets input autofocus

- frontend/src/components/common/AlertDialog.tsx
- frontend/src/components/editables/EditorHeader.tsx
- frontend/src/components/editables/assets/AssetEditor.tsx
- frontend/src/components/editables/assets/AssetInfoBar.tsx
- frontend/src/utils/editables/useDeleteEditableObjectWithUserInteraction.ts
Task: https://10clouds.atlassian.net/browse/ACD-445
> feat: confirmation modal improvement

- frontend/src/components/editables/chat/AgentAvatar.tsx
- frontend/src/components/editables/chat/EmptyChat.tsx
**Task:** [ACD-881](https://10clouds.atlassian.net/browse/ACD-881)
**Preview:**
[ACD-881]: https://10clouds.atlassian.net/browse/ACD-881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: agent icon improvement

- frontend/src/components/editables/chat/AgentAvatar.tsx
- frontend/src/components/projects/ProjectCard.tsx
- frontend/tailwind.config.js
Task: https://10clouds.atlassian.net/browse/ACD-484
> feat: restyling recent project item card

- frontend/src/components/common/TopBar.tsx
- frontend/src/components/projects/Home.tsx
- frontend/src/components/projects/ProjectCard.tsx
- frontend/src/components/projects/RecentProjectsEmpty.tsx
- frontend/tailwind.config.js
**Task:** [ACD-879](https://10clouds.atlassian.net/browse/ACD-879)
**Preview:**
https://github.com/10clouds/aiconsole/assets/63242859/60b6bb2d-8d5c-473c-aca9-c17719110b9e
[ACD-879]: https://10clouds.atlassian.net/browse/ACD-879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update home layout and H1 font size

- frontend/src/components/editables/chat/MessageGroup.tsx
> fix: add padding to chat window container

- frontend/src/components/editables/assets/CodeInput.tsx
> fix: change button postion in agent editor

- frontend/package.json
- frontend/src/components/editables/assets/Autocomplete.tsx
- frontend/src/components/editables/assets/ChatOptions.tsx
- frontend/src/components/editables/sidebar/ChatsSidebarTab.tsx
- frontend/src/components/editables/sidebar/SideBar.tsx
- frontend/src/index.css
- frontend/yarn.lock
**Issue:** #359 (improvements after @cielecki's [comment](https://github.com/10clouds/aiconsole/issues/359#issuecomment-1873522823))
**Preview:**
https://github.com/10clouds/aiconsole/assets/63242859/a8eedcb4-cdbd-4732-9224-c644e0c8a84b
> feat: force agent and materials per chat - improvements

- backend/aiconsole/consts.py
- backend/aiconsole/preinstalled/materials/environment.py
* fix(aiconsole/consts.py): handle ImportError for GPTMode in a try-except block
* refactor(preinstalled/materials/environment.py): remove unnecessary datetime module import
> 🔌 Electron's bundle python requires pydantic installed 🐍💼

- electron/src/main.ts
> feat: close all app windows

- frontend/src/components/editables/assets/CodeInput.tsx
> fix: change preview button position

- frontend/package.json
- frontend/src/components/editables/assets/MarkdownPreview.tsx
- frontend/src/components/editables/chat/messages/MessageComponent.tsx
- frontend/yarn.lock
> fix: dont transform markdown links

- frontend/src/components/common/Toast.tsx
> fix: remove notifications truncation

- frontend/src/components/common/AlertDialog.tsx
- frontend/src/components/common/Button.tsx
- frontend/src/components/common/icons/MarkdownLogo.tsx
- frontend/src/components/editables/MarkdownSupported.tsx
- frontend/src/components/editables/assets/AgentForm.tsx
- frontend/src/components/editables/assets/AssetEditor.tsx
- frontend/src/components/editables/assets/AssetInfoBar.tsx
- frontend/src/components/editables/assets/CodeInput.tsx
- frontend/src/components/editables/assets/MaterialForm.tsx
#542
#458 
#457
#360 
+ other small styling fixes
> Asset editor fixes

- frontend/src/components/common/Button.tsx
- frontend/src/components/common/Select.tsx
- frontend/src/components/editables/assets/AddAssetDropdown.tsx
- frontend/src/components/editables/assets/AgentForm.tsx
- frontend/src/components/editables/assets/ChatOptions.tsx
- frontend/src/components/editables/assets/CodeInput.tsx
- frontend/src/components/editables/assets/MarkdownPreview.tsx
- frontend/src/components/editables/chat/messages/MessageComponent.tsx
- frontend/src/utils/common/cn.ts
> fix: asset editor styles

- frontend/src/components/editables/chat/Analysis.tsx
- frontend/src/components/editables/chat/MessageGroup.tsx
- frontend/src/index.css
[#503 ](https://github.com/10clouds/aiconsole/issues/503)
> feat: create analysis message

- frontend/src/components/settings/modal/GlobalSettingsModal.tsx
> fix: global settings modal refactor

- frontend/src/components/editables/chat/ChatPage.tsx
> fix: update confirmation buttons labels in ChatPage's dialog

- frontend/src/components/projects/Home.tsx
- frontend/src/components/projects/ProjectCard.tsx
- frontend/src/types/projects/RecentProject.ts
[378](https://github.com/10clouds/aiconsole/issues/378)
> feat: add icons and info about recent projects

- frontend/src/components/common/ImageUploader.tsx
- frontend/src/components/editables/InlineEditableObjectName.tsx
- frontend/src/components/editables/assets/AssetEditor.tsx
- frontend/src/components/editables/assets/AssetInfoBar.tsx
- frontend/src/components/editables/assets/CodeInput.tsx
- frontend/src/components/editables/assets/MaterialForm.tsx
- frontend/src/components/editables/assets/TextInput.tsx
> fix: asset editor settings labels

- frontend/src/components/editables/chat/ChatPage.tsx
- frontend/src/utils/editables/useAssetChanged.tsx
[648](https://github.com/10clouds/aiconsole/issues/648)
> fix: updating chatsidebartab

- electron/forge.config.cjs
- electron/package.json
- electron/yarn.lock
https://github.com/10clouds/aiconsole/issues/656
> Remove zip files from the release assets

- frontend/src/components/projects/ProjectButtons.tsx
- frontend/src/store/projects/useProjectStore.ts
- frontend/src/utils/projects/useProjectFileManager.ts
> refactor: project choosing logic

- backend/aiconsole/core/chat/execution_modes/interpreter.py
- backend/aiconsole/core/code_running/code_interpreters/subprocess_code_interpreter.py
- backend/aiconsole/core/settings/fs/settings_file_storage.py
- backend/aiconsole/preinstalled/materials/dalle_3_image_generator.py
- backend/aiconsole/preinstalled/materials/dalle_3_image_generator.toml
- backend/aiconsole_toolkit/settings/__init__.py
* fix(interpreter.py): adjust description for python CodeTask to fix formatting 
* feat(interpreter.py): add temperature parameter to generate_response for more consistency in responses 
* refactor(interpreter.py): simplify function call handling logic
> Inconsistent code format output from Automator

- backend/aiconsole/api/websockets/incoming_message_handler.py
- backend/aiconsole/core/chat/apply_mutation.py
- backend/aiconsole/core/chat/execution_modes/example_countdown.py
- backend/aiconsole/core/chat/execution_modes/interpreter.py
- backend/aiconsole/core/chat/execution_modes/normal.py
- frontend/src/components/editables/chat/messages/MessageComponent.tsx
> Backend is_streaming implementation for WS messaging

- frontend/src/components/Router.tsx
- frontend/src/components/editables/chat/ChatPage.tsx
- frontend/src/components/editables/chat/EmptyChat.tsx
**Issue:** #687 
**Preview:**
https://github.com/10clouds/aiconsole/assets/63242859/502b806f-f074-47e9-8a80-c7f6d6efa6a5
> fix: chats sidebar flickering

- frontend/src/components/projects/ProjectCard.tsx
> feat: add dynamic agents' avatars in project card

- frontend/src/components/common/BackgroundGradient.tsx
- frontend/src/components/projects/Home.tsx
> fix: remove horizontal scrollbars

- frontend/src/components/editables/assets/ChatOptions.tsx
- frontend/src/components/editables/chat/CommandInput.tsx
- frontend/src/components/editables/chat/messages/ToolCall.tsx
[359](https://github.com/10clouds/aiconsole/issues/359)
[734](https://github.com/10clouds/aiconsole/issues/734)
> fix: font size

- electron/src/main.ts
- electron/src/preload.ts
- frontend/src/components/editables/assets/AssetEditor.tsx
- frontend/src/index.d.ts
**Issue:** #737 
**Preview:**
https://github.com/10clouds/aiconsole/assets/63242859/dfb585b6-a085-4821-b64b-21588dd4d9bf
> feat: confirmation modal on close with unsaved changes

- frontend/src/components/editables/assets/TextInput.tsx
> fix: TextInput's label width adjustment

- frontend/src/components/editables/assets/TextInput.tsx
- frontend/src/components/projects/Home.tsx
[750](https://github.com/10clouds/aiconsole/issues/750)
[762](https://github.com/10clouds/aiconsole/issues/762)
> fix: alert name button

- frontend/src/components/editables/chat/messages/MessageComponent.tsx
[793](https://github.com/10clouds/aiconsole/issues/793)
> fix: formatting list on displaying messages

- backend/aiconsole/api/endpoints/assets/chat_options.py
- backend/aiconsole/core/chat/load_chat_options.py
- backend/aiconsole/core/chat/locking.py
- backend/aiconsole/core/chat/types.py
- frontend/src/api/api/ChatAPI.ts
- frontend/src/components/assets/chat/ChatPage.tsx
- frontend/src/components/assets/chat/CommandInput.tsx
- frontend/src/store/assets/chat/ChatSlice.ts
- frontend/src/store/assets/useAssetStore.ts
- frontend/src/types/assets/chatTypes.ts
Implemented draft message as a chat_option @udislau
> feat: add draft command chat option

- frontend/src/components/assets/chat/CommandInput.tsx
**Issue:** #890 
**Preview:**
https://github.com/10clouds/aiconsole/assets/63242859/a3828590-dd81-47fd-9529-17ea37c46153
**Note:** apart from the bugfix, I have also sorted the store hooks to improve readability.
> fix: keep textarea's caret position when typing

- backend/aiconsole/api/endpoints/net_check.py
- backend/aiconsole/api/routers.py
- frontend/src/api/api/UtilsAPI.ts
- frontend/src/components/common/Button.tsx
- frontend/src/components/common/icons/NoInternet.tsx
- frontend/src/components/projects/Home.tsx
- frontend/src/components/projects/Offline.tsx
- frontend/src/components/projects/RecentProjectsEmpty.tsx
- frontend/src/store/common/useUtilsStore.ts
**Issue:** #891 
**Preview:**
https://github.com/10clouds/aiconsole/assets/63242859/c3b63165-a29b-4658-904e-4c65df8eef49
> feat: add "no internet connection" screen
